---
port_profiles:
  TENANT_A_B:
    mode: trunk
    vlans: "110-111,210-211"
  TENANT_A:
    mode: access
    vlans: "110"

servers:

  - name: VPC7
    adapters:
    - endpoint_ports:
      - LAN
      mode: access
      spanning_tree_bpduguard: enabled
      spanning_tree_portfast: edge
      switch_ports:
      - Ethernet5
      switches:
      - DC1-LEAF1A
      vlans: '110'

  - name: VPC8
    adapters:
    - endpoint_ports:
      - LAN
      mode: access
      spanning_tree_bpduguard: enabled
      spanning_tree_portfast: edge
      switch_ports:
      - Ethernet5
      switches:
      - DC1-LEAF2B
      vlans: '110'
